config/routes.rb
Rails.application.routes.draw do
  resources :followers
  resources :tweets
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get '/users/search', to: 'users#search'
  get 'users/followers', to: 'users#followers'
  get 'users/following', to: 'users#following'
  resources :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
    @users_map = {}
    @tweets.each do |tweet|
      user_id = tweet.user_id
      @users_map[user_id] = User.find(user_id)
    end
  end

  # GET /tweets/1 or /tweets/1.json
  def show
    @user = User.find(@tweet.user_id)
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
      @is_my_tweet = user_signed_in? && current_user.id == @tweet.user_id
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :content)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
    <%= form.hidden_field :user_id, required: true, class: 'form-control', value:current_user.id  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>
<div class="title-container">
  <h1>Tweets</h1>
</div>

<div class="tweets">
  <dl>
    <% @tweets.each do |tweet| %>
      <div class='tweet">
        <div class="thumbnail">
          <div class="cpation">
          <%user = @users_map[tweet.user_id]%>
            <dt><h4><%=link_to user.username, user_path(user) %></h4></dt>
            <dd><p><%=truncate(tweet.content)%></p></dd>
            <p>
            <%if current_user.id == user.id %>
              <td><%= link_to 'Edit', edit_tweet_path(tweet), class: "btn btn-default" %></td>
              <td><%= link_to 'Delete', tweet, class: "btn btn-default", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end%>
            </p>
          </div>
        </div>
      </div>
    <%end%>
  </dl>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.username || "" %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<%if @is_my_tweet%>
  <%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%end%>
<%= link_to 'Back', tweets_path %> |
<%= link_to "visit user profile", user_path(@user)%>