config/routes.rb
Rails.application.routes.draw do
  resources :followers
  resources :tweets
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get '/users/search', to: 'users#search'
  get 'users/followers', to: 'users#followers'
  get 'users/following', to: 'users#following'
  resources :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    validates_presence_of :username
    validates_presence_of :password
    validates_format_of :password, :with => /[a-z0-9]{6,20}/
    
  has_many :tweets
  has_many :followers
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy following followers ]
  before_action :set_following, only: %i[ show following followers ]
  before_action :set_followers, only: %i[ show followers following ]
  before_action :set_is_follow, only: %i[ show followers following ]
  before_action :searched_users, only: %i[ search ]

  Q_GET_ALL_FOLLOWERS = 'follow = ?'
  Q_GET_ALL_FOLLOWING = 'user_id = ?'

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @followers_count = @followers.length() || 0
    @following_count = @following.length() || 0
    @tweets = Tweet.where("user_id = ?", @user.id)
  end

  # GET /users/search
  def search
  end

  # GET /users/followers
  def followers
    @users = []
    if !@followers.blank?
      @followers.each do |follower|
        user_id = follower.user_id
        user = User.find(user_id)
        if !user.blank?
          @users.append(user)
        end
      end
    end
  end

  # GET /users/following
  def following
    @users = []
    if !@following.blank?
      @following.each do |follower|
        user_id = follower.follow
        user = User.find(user_id)
        if !user.blank?
          @users.append(user)
        end
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_following
      @following = Follower.where(Q_GET_ALL_FOLLOWING, @user.id)
    end

    def set_followers
      @followers = Follower.where(Q_GET_ALL_FOLLOWERS, @user.id)
    end

    def set_is_follow
      if @followers.length() || 0 > 0
        current_user_following = @followers.where("user_id = ?", current_user.id)
        @is_follow = !current_user_following.blank?
        if @is_follow
          @follow_row_index = current_user_following.first.id
        end
      else
        @is_follow = false
      end
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password)
    end

    def searched_users
      @users = User.where("username LIKE ?", "%#{params[:q]}%")
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(url: users_path) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email%>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.pasword_field :password%>
  </div>

  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/followers.html.erb
<p id="notice"><%= notice %></p>

<h1>Followers</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'back', user_path(@user) %>   

app/views/users/following.html.erb
<p id="notice"><%= notice %></p>

<h1>Followeing</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'visit user profile', user %></td> 
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'back', user_path(@user) %>   

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="title-container">
  <h1>Users</h1>
</div>
<div class="users">
  <% @users.each do |user| %>
    <div class="user">
      <div class="thhumbnail">
        <div class="caption">
          <h3><%= link_to user.username, user %></h3>
          <br/>
          <p>
            <% if current_user.id == user.id %>
            <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-default" %></td> 
            <td><%= link_to 'Delete', user, class: "btn btn-default", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </p>
        </div>
      </div>
    </div>
    <br/>
  <%end%>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <%if user_signed_in?%>
            <%if current_user.id == user.id%>
                <td><%= link_to 'Edit', edit_user_path(user) %></td>
                <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end%>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>User Email:</strong>
  <%= @user.email %>
</p>

<p>      
  <strong>Followers:</strong>
  <br>
  <%= button_to "#{@followers_count}", users_followers_path, params: {id: @user.id}, method: :get %>
  </br>
</p>

<p>
  <strong>Following:</strong>
  <%= button_to "#{@following_count}", users_following_path, params: {id: @user.id}, method: :get %>
</p>

<p>
  <strong>Tweets:</strong>
  <br/><br/>
  <% @tweets.each do |tweet| %>
    <%= tweet.created_at.strftime("%d/%m/%Y") %>: <%= tweet.content %>
    <br/>
  <% end%>
</p>


<%if user_signed_in?%>
  <%if current_user.id == @user.id%>
    <%= link_to 'Edit', edit_user_path(@user) %> |
  <%else%>
    <% if !@is_follow %> 
      <%= button_to "follow", followers_path(follower: {user_id: current_user.id,follow: @user.id}) %>
    <%else%>
      <%= button_to "unfollow", follower_url(@follow_row_index), method: :delete, data: { confirm: 'Are you sure?' }  %>
    <%end%>
  <%end%>
<%end%>
<%= link_to 'Back', users_path %>