config/routes.rb
Rails.application.routes.draw do
  resources :followers
  resources :tweets
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get '/users/search', to: 'users#search'
  get 'users/followers', to: 'users#followers'
  get 'users/following', to: 'users#following'
  resources :users
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/follower.rb
class Follower < ApplicationRecord
    belongs_to :user
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :set_follower, only: %i[ show edit update destroy ]

  # GET /followers or /followers.json
  def index
    @followers = Follower.all
  end

  # GET /followers/1 or /followers/1.json
  def show
  end

  # GET /followers/new
  def new
    @follower = Follower.new
  end

  # GET /followers/1/edit
  def edit
  end

  # POST /followers or /followers.json
  def create
    @follower = Follower.new(follower_params)

    respond_to do |format|
      if @follower.save
        user = User.find(@follower.follow)
        format.html { redirect_to user_url(user)}
        format.json { render :show, status: :created, location: user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /followers/1 or /followers/1.json
  def update
    respond_to do |format|
      if @follower.update(follower_params)
        format.html { redirect_to follower_url(@follower), notice: "Follower was successfully updated." }
        format.json { render :show, status: :ok, location: user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followers/1 or /followers/1.json
  def destroy
    user = User.find(@follower.follow)
    @follower.destroy

    respond_to do |format|
      format.html { redirect_to user_url(user)}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follower
      @follower = Follower.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def follower_params
      params.require(:follower).permit(:user_id, :follow)
    end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/views/followers/_form.html.erb
<%= form_with(model: follower) do |form| %>
  <% if follower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(follower.errors.count, "error") %> prohibited this follower from being saved:</h2>

      <ul>
        <% follower.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :follow %>
    <%= form.number_field :follow %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/followers/edit.html.erb
<h1>Editing Follower</h1>

<%= render 'form', follower: @follower %>

<%= link_to 'Show', @follower %> |
<%= link_to 'Back', followers_path %>

app/views/followers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Followers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Follow</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followers.each do |follower| %>
      <tr>
        <td><%= follower.user_id %></td>
        <td><%= follower.follow %></td>
        <td><%= link_to 'Show', follower %></td>
        <td><%= link_to 'Edit', edit_follower_path(follower) %></td>
        <td><%= link_to 'Destroy', follower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follower', new_follower_path %>

app/views/followers/new.html.erb
<h1>New Follower</h1>

<%= render 'form', follower: @follower %>

<%= link_to 'Back', followers_path %>

app/views/followers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @follower.user_id %>
</p>

<p>
  <strong>Follow:</strong>
  <%= @follower.follow %>
</p>

<%= link_to 'Edit', edit_follower_path(@follower) %> |
<%= link_to 'Back', followers_path %>